title:            Escuela Social Ramón Fernández Durán
description:      "La Escuela de los Movimientos Sociales"
logo:             logo.png
disqus_shortname: escuelaramonfdez
share:            true
#dropcap:          true

baseurl:        /
url:       


# Owner/author information
owner:
  name:           Escuela Social Ramón Fernández Durán
  avatar:         logo.png
  email:          escuela.ramon.fdez@gmail.com
  # Use the coder's toolbox at http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
  description:    "Una escuela para la formación, reflexión y acción colectiva de los movimientos sociales."
  # Social networking links used in footer. Update and remove as you like.
  twitter:        escuelaramonfde
  facebook:       1155402361213973
  github:         escuelaramonfdez
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    https://plus.google.com/u/0/b/105797341966853173647

# Analytics and webmaster tools stuff goes here
# google_analytics:   UA-39365944-7
#google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
#bing_verify:         

# Links to include in footer navigation
# For external links add external: true
links:
  - title: Inicio
    url: /
    external: false
    icon: home
  - title: Presentación
    url: /presentacion
  - title: Contenidos
    url: /contenidos
  - title: Logística
    url: /logistica
  - title: Inscripción
    url: /inscripcion

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Madrid
future:      true
highlighter: pygments
markdown:    kramdown
paginate:    5
paginate_path: "page:num"

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

prose:
  rooturl: '_posts'
  siteurl: 'http://escuela-ramon-fdez.github.io/'
  relativeLinks: 'http://escuela-ramon-fdez.github.io/links.jsonp'
  media: 'images'
  metadata:
    _posts:
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: "true"
      - name: "layout"
        field:
          element: "hidden"
          label: "Layout"
          value: "post"
      - name: "title"
        field:
          label: "Title"
          element: "text"
          value: "Un título impactante"
      - name: "description"
        field:
          element: "text"
          label: "Description"
          placeholder: "Introducir descripción del post"
      - name: "modified"
        field:
          element: "text"
          label: "¿Ha sido modificada la página?"
          placeholder: "YYYY-MM-DD"
      - name: "tags"
        field:
          element: "text"
          label: "Tags"
          placeholder: "Introducir las palabras clave separadas por espacio"
      - name: "imagefeature"
        field:
          element: "text"
          label: "Imagen"
          placeholder: "somefile.jpg"
      - name: "mathjax"
        field:
          element: "checkbox"
          label: "MathJax"
          value: false
      - name: "featured"
        field:
          element: "checkbox"
          label: "Featured?"
          value: false
      - name: "comments"
        field:
          element: "checkbox"
          label: "Comments"
          value: false


include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
